version: "3.8"

services:
  backend:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    command: sh -c "go run main.go migrate && go run main.go initdata && air -c .air.toml serve"
    ports:
      - 5000:5000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - app-postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - db
  #   expose:
  #     - 5050
  #   ports:
  #     - 5050:5050
  #   environment:
  #     - PGADMIN_LISTEN_PORT=5050
  #     - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   volumes:
  #     - app-pgadmin-data:/var/lib/pgadmin
  #   restart: unless-stopped

volumes:
  app-postgres-data:
  # app-pgadmin-data:
