FROM golang:1.20-alpine as builder

WORKDIR /app

RUN go install github.com/roerohan/wait-for-it@v0.2.13

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml", "serve"]

COPY ./ .

RUN go build -o /app/go-boilerplate

FROM golang:1.20-alpine as runtime

WORKDIR /app

COPY --from=builder /app/go-boilerplate /app/go-boilerplate
COPY --from=builder /go/bin/wait-for-it /go/wait-for-it

RUN mkdir config
COPY ./config/config.default.yml /app/config/
